apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: schedule greeting

on:
  schedule:
    - cron: "6,12,18,24,30,36,42,48,54 * * * *"

jobs:
  greet:
    steps:
    - name: greet
      uses: docker://alpine:3.20
      run: echo "hello"