apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: other greeting

on:
  schedule:
    - cron: "0,15,30,45 * * * *"

jobs:
  greet:
    steps:
    - name: greet
      uses: docker://alpine:3.20
      run: echo "hello"